# Config for rustfmt 0.8.2-nightly (08da30d 2018-06-06).
required_version = "0.8.2"
unstable_features = true

blank_lines_upper_bound = 2
error_on_line_overflow = false  # Default.
match_block_trailing_comma = true
newline_style = "Unix"  # Default.
reorder_imports = true  # Default.
reorder_modules = true  # Default.
trailing_comma = "Vertical"  # Default.
wrap_comments = true
